### ISSUE TITLE
product_supplierinfo_for_customer : incorrect price on sale order

### ISSUE THREAD

**Issue by gurneyalex** [OCA/product-attribute#1115]
Incorrect price on sale order when using product_supplierinfo_for_customer

## Describe the bug

When configuring a customers "supplierinfo" the sales price is not used in quotation 

## To Reproduce
**Affected versions**: 15.0 (at least)

1. on runboat 15.0 branch of this repository, install the sales application
2. edit the product "4 persons desk" to set some customer supplier info like this:
![image](https://user-images.githubusercontent.com/2032807/178697674-9f0010ad-e545-46bd-a9d9-58bbf3470dae.png)
3. (notice the price of 22USD)
4. create a quotation for the customer on which you added the information in the product, and add the 4 person desk product inside

**Expected behavior**

The price on the sale order line is 22USD

**Observed behavior** 

The price is the public price from the product information
![image](https://user-images.githubusercontent.com/2032807/178698185-b3803d27-5b9d-40fe-b306-bc5ffb14e908.png)

**Comment by pedrobaeza** [comment]
Maybe the problem is that you are not configuring the pricelist to "Partner Prices on the product form"?

https://github.com/OCA/product-attribute/blob/15.0/product_supplierinfo_for_customer/models/product_pricelist.py#L12
