### ISSUE TITLE
[12.0-13.0-14.0][IMP] product_state: improve security groups?

### ISSUE THREAD

**Issue by HekkiMelody** [OCA/product-attribute#1121]
**Is your feature request related to a problem?**
https://github.com/OCA/product-attribute/blob/14.0/product_state/security/ir.model.access.csv
Currently, Create Write and Delete permissions are given to `base.group_partner_manager`. That group's name is "Contact Creation" and doesn't seem at all related with managing product states

**Describe the solution you'd like**
I'd suggest changing the security group to "inventory manager" (`stock.group_stock_manager`) instead. Seems like a better default, unless there's a reason I'm not aware of. I'd be happy to make the PR myself if it seems like a good change.

**Comment by BT-mgomez** [comment]
Hello, I agree on this.
I saw this access right was introduced in v12 and is up to v15. 
Is there a way to track this down and someone who will decide on this issues? 

Was going to create the same issue, but for v15, then just found this one.
