### ISSUE TITLE
[14.0] product_supplierinfo_group breaks product_supplierinfo_for_customer

### ISSUE THREAD

**Issue by ilyasProgrammer** [OCA/product-attribute#1135]
## Module
product_supplierinfo_group 

## Describe the bug
- Module breaks "Create customer info" form. All relational fields turns to read only.
- If you force these fields to be editable (edit form and set readonly="0" for all fields) and try to save customer info record, you will get error: ERROR: null value in column "product_tmpl_id" violates not-null constraint

## To Reproduce
**Affected versions**:
14.0.2.0.1

Install product_supplierinfo_group and product_supplierinfo_for_customer

1. Open product
2. Sales tab
3. Fixed Price table - click Add line. You will see not editable form.

**Expected behavior**
All fields should be editable.
You should be able to save record.

**Comment by francesco-ooops** [comment]
@mourad-ehm @kevinkhao @sebastienbeau any suggestions to solve this?

**Comment by francesco-ooops** [comment]
solved here https://github.com/OCA/product-attribute/pull/1169
