### ISSUE TITLE
Product ABC Classification - Why levels are assigned automatically in descending order when it should be the other way around?

### ISSUE THREAD

**Issue by karsanpav** [OCA/product-attribute#1147]
module: product_abc_classification
version: 13.0

**Steps to reproduce**
- Choose **Percentage** classification type
- Create 3 Levels: **10**/**20**/**70**

**Current behavior**
The assignation of levels is:
A - 70 %
B - 20 %
C - 10 %

**Expected behavior**
The assignation of levels should be:
A - 10 %
B - 20 %
C - 70 %

Or maybe there could be a way to reassign the levels like, change the sequence of each or modify the Level value when is already assigned.

**Comment by pedrobaeza** [comment]
You usually want to see first the products with more sales than the less important ones, so I think the order is correct.

**Comment by karsanpav** [comment]
Thank you, Pedro, I was misunderstanding the percentage classification. It refers to the percentage of sales, not the percentage of references.
