### ISSUE TITLE
product_pricelist_direct_print : Add new features

### ISSUE THREAD

**Issue by legalsylvain** [OCA/product-attribute#1152]
Hi all,

First thanks for the module ``product_pricelist_direct_print``. That's a great module.

I'd like to use this module, but I need extra features : 

- the module display the sale price of the product. (ref : [xml](https://github.com/OCA/product-attribute/blob/14.0/product_pricelist_direct_print/views/report_product_pricelist.xml#L92) and [xlsx](https://github.com/OCA/product-attribute/blob/14.0/product_pricelist_direct_print/report/product_pricelist_xlsx.py#L105)). In my context, price are set in B2C. (price are vat incl). However, I'd like to edit pricelist for B2B (vat excl) or B2C (vat incl). I propose to add an option ``fiscal_position_id`` in the wizard model, and then compute the sale price depending on the fiscal position defined. What do you think ?

- I'd like to group product list by other field that the categ_id of the product. For the time being, the group by is hardcoded [here](https://github.com/OCA/product-attribute/blob/14.0/product_pricelist_direct_print/wizards/product_pricelist_print.py#L308). I'd like to introduce a new field in the wizard model ``group_by_field = field.selection(selection=[('categ_id', 'Category')], default='categ_id', required=True)]``  that could be overloaded to add other field. (for exemple ``pos_categ_id`` or any custom field. Are you ok with such implementation ? 

CC original contributors  : @sergio-teruel, @CarlosRoca13, @carlosdauden, @chienandalu, @ernestotejeda, @alexey-pelykh

I plan to target the V12 and then to port such improvment in V16.

**Comment by chienandalu** [comment]
Your contributions are allways wellcome @legalsylvain and your proposal looks perfectly reasonable to me :smile: :+1:

**Comment by legalsylvain** [comment]
Hi @chienandalu : here is a PR #1177. I'll be glad if you could take a look on it. 

Thanks !

**Comment by legalsylvain** [comment]
PR merged. Closing.
