### ISSUE TITLE
product_packaging_type: Migrate to 16.0

### ISSUE THREAD

**Issue by rousseldenis** [OCA/product-attribute#1213]
@jgrandguillaume I want your advice here.

As package type is standard now in Odoo, I'm wondering what name given to the product_packaging_type module as some features are missing in core.

Should we keep the original name, choose a name like stock_package_type_oca, or ... ?

**Comment by rousseldenis** [comment]
> @jgrandguillaume I want your advice here.
> 
> As package type is standard now in Odoo, I'm wondering what name given to the product_packaging_type module as some features are missing in core.
> 
> Should we keep the original name, choose a name like stock_package_type_oca, or ... ?

After first discussion, it has more common sense to split per introduced functionallity.

So, at first sight stock_package_type_gtin, stock_package_type_default, stock_pacakge_type_quantity

@sebalix @grindtildeath @jbaudoux @gurneyalex @lmignon

**Comment by rousseldenis** [comment]
And is it too soon to require a separate repository for this ?

**Comment by jbaudoux** [comment]
The right name should be product packaging level.
But as there was already package level in odoo, to prevent confusion, we opt for packaging type. Now that this name exist also in standard odoo, I would go back to the common name "product_packaging_level"

And I would not split the module.

**Comment by rousseldenis** [comment]
> The right name should be product packaging level. But as there was already package level in odoo, to prevent confusion, we opt for packaging type. Now that this name exist also in standard odoo, I would go back to the common name "product_packaging_level"
> 
> And I would not split the module.

@jbaudoux So, to be clear, it's not the same as in core :

![image](https://user-images.githubusercontent.com/19529533/203752392-8b2fc955-2bec-47d8-a2ac-1c306821a8be.png)

**Comment by rousseldenis** [comment]
And it's not comparable as :

![image](https://user-images.githubusercontent.com/19529533/203753334-7eef1e5f-cd3d-44e5-af41-51001babf5b5.png)

**Comment by jbaudoux** [comment]
Indeed. On the product packaging, we will have the core `package_type_id` which defines the put-away rule for storing the goods. And the new `package_level_id` which defines if it is a consumer unit, a transport box or a pallet. That package level will serve in the SO and PO to express if you want to sell / purchase a multiple of consumer unit, box, or pallets

**Comment by rousseldenis** [comment]
> Indeed. On the product packaging, we will have the core `package_type_id` which defines the put-away rule for storing the goods. And the new `package_level_id` which defines if it is a consumer unit, a transport box or a pallet. That package level will serve in the SO and PO to express if you want to sell / purchase a multiple of consumer unit, box, or pallets

Ok, so let's go for product_packaging_level
