### ISSUE TITLE
[16.0] product_logistics_uom: Introduces inconsistencies 

### ISSUE THREAD

**Issue by lmignon** [OCA/product-attribute#1312]
## Module
product_logistics_uom

## Describe the bug

In odoo 16 at least, default uoms are defined into the config parameters for volume and weight and length.  To ensure consistencies between values for such a field, values into the database should always be stored into the default uom. 
The `product_logistics_uom` addon reintroduce new default config parameter and allows to store the product's volume an weight into an other uom that the system default. 

Even if we want to allow the user to choose the volume and weight uom per product, the value stored into the DB must be expressed into the default uoms.

**Expected behavior**
At least 16.0

**Comment by hparfr** [comment]
It not a bug it a feature. 

If you have bottle of 33cl, it will be 0 m³.

**Comment by lmignon** [comment]
IMO It's a bug. You can express your value in cl and store-it in m3.  Or you can decide at system level you manage your uom in cl. You also have the possibility to increase the decimal precision of your default system uom to be sure to not lose your value into the conversion process from one to another value.  If you don't do this, the weight computed for example by odoo in the deflivery addon for the delivery package will be wrong.

**Comment by hparfr** [comment]
Yes but increasing the decimal precision of storage uom is not without side effects.
