### ISSUE TITLE
Missing @api.depends_context("product")

### ISSUE THREAD

**Issue by pasculorente** [OCA/product-attribute#1421]
https://github.com/OCA/product-attribute/blob/855790cac520af347b069a2931206429091d5bc2/product_pricelist_direct_print/wizards/product_pricelist_print.py#L84

I installed this module but the prices for the products were all the same, adding `@api.depends_context("product")` fixed it

**Comment by legalsylvain** [comment]
Hi @pasculorente. could you make a PR ? 
thanks !

**Comment by pasculorente** [comment]
@legalsylvain  https://github.com/OCA/product-attribute/pull/1422
