### ISSUE TITLE
product_company_default is in V16 but not V15

### ISSUE THREAD

**Issue by Atteqany** [OCA/product-attribute#1448]
This is a call to the respected distributed to provide product_company_default for V15 as it is in V16 

This module is very helpful in multi-company Odoo instances. It will populate the company field with user’s company as the default value when creating new products. So the product will not appear for other users in other companies.

**Comment by pedrobaeza** [comment]
Check the issue for the migration to track the progress, or fund the authors to speed up the migration.

**Comment by CarlosRiquelme** [comment]
Hello, can I downgrade from version 16 to 15. I'm opening an issue for migration.
