### ISSUE TITLE
[product_pricelist_fixed_price][8.0] onchange of base_ext function has newId for self

### ISSUE THREAD

**Issue by stijnh92** [OCA/product-attribute#145]
In the onchange function of the field base_ext, the id of the current object is set to newId.
I put a breakpoint in my code to find the error and noticed the following:
![error_pricelist](https://cloud.githubusercontent.com/assets/8638753/14274226/6207a684-fb10-11e5-9c8c-8bb76ebcf237.png)

Because of this, when setting the base_ext to fixed price, the field 'other pricelist' is still required and visible.
Note: this only happens when adding an item starting from product.pricelist, then selecting the product.pricelist.version and then adding a new product.pricelist.item.
This does not happen when opening the product.pricelist.version directly and adding a new pricelist item.

**Comment by pedrobaeza** [comment]
@NL66278, your last PR seems to be causing this. Can you please check?

**Comment by pedrobaeza** [comment]
@NL66278, please fix 8.0 branch tests

**Comment by NL66278** [comment]
@pedrobaeza I will do. Allow for some time, as I am away from work until sunday.

**Comment by pedrobaeza** [comment]
OK, sorry. It's just the red branch is choking on each new PR and I come back here when happens.

**Comment by pedrobaeza** [comment]
I have fixed the issue directly in the commit https://github.com/OCA/product-attribute/commit/037e77ce2aa6dd110fa7394f790f94108afdb20f, because it was bitten me each time with my current PRs.
