### ISSUE TITLE
product_main_supplierinfo typo

### ISSUE THREAD

**Issue by sergiocorato** [OCA/product-attribute#1460]
https://github.com/OCA/product-attribute/blob/ea0f7f683107315ac7cba305742c7c85f58bbd30/product_main_supplierinfo/models/product_product.py#L54

**Comment by legalsylvain** [comment]
@TDu : could you take a look on this one  ?

**Comment by rvalyi** [comment]
fixed by https://github.com/OCA/product-attribute/pull/1524
