### ISSUE TITLE
How to install this module? Can't find installation instructions.

### ISSUE THREAD

**Issue by gantulgan** [OCA/product-attribute#149]
module: product_multi_category
version: 9.0

**Steps to reproduce**
- Download the module. Unzip contents into the [odoo_path]/addons/ directory.

**Current behavior**
Not able to see the module in my install-able app list in my OdooErp.

**Expected behavior**
Module show up on the Apps list and be able to install this module into my OdooErp or able to add multiple categories on a product. 

Sorry, if the question is too simple. I couldn't find a instructions so far.

Thanks, for your help :D

**Comment by pedrobaeza** [comment]
This is not for asking for help. It's for reporting issues.
