### ISSUE TITLE
V16 branch looks broken

### ISSUE THREAD

**Issue by legalsylvain** [OCA/product-attribute#1513]
hi all.

Since recent changes, V16.0 looks broken : 
https://github.com/OCA/product-attribute/actions/workflows/test.yml?query=branch%3A16.0

So, all the new PR against V16 branch are failing : 
- https://github.com/OCA/product-attribute/pull/1512
- https://github.com/OCA/product-attribute/pull/1511
- https://github.com/OCA/product-attribute/pull/1505 by @SilvioC2C 
- https://github.com/OCA/product-attribute/pull/1510 by @ChrisOForgeFlow 

I dig a little bit on the logs, but did'nt found the origin of the problem.

@OCA/product-maintainers : could you take a look ? @jjscarafia, @JordiBForgeFlow, @rousseldenis, @gurneyalex

Thanks ! 

Note : BTW, there are also weird warning, related to incorrect call of ``digits``, but I don't understand why...

``2024-01-29 11:40:27,563 425 WARNING odoo odoo.fields: Field wizard.preview.pricelist.line.price: unknown parameter 'digits', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it ``

**Comment by simahawk** [comment]
The warning has been fixed in #1521 .
The error seems to come from `abc_classification_product_level`
[OCA/product-attribute/actions/runs/7955666562/job/21715009413?pr=1521#step:8:480](https://github.com/OCA/product-attribute/actions/runs/7955666562/job/21715009413?pr=1521#step:8:480)

**Comment by simahawk** [comment]
Plenty of errors in fact... I've tried to move on in #1521

**Comment by legalsylvain** [comment]
Thanks !
