### ISSUE TITLE
IMP : Add a new src_model attribute on Active Window(more options) for product.brand and product.product model

### ISSUE THREAD

**Issue by cdasadiya** [OCA/product-attribute#162]
module: product_brand
version: 8.0

**Steps to reproduce**
- ...

**Current behavior**
Currently Product Brand Module Having the Logic for View the Following criteria on more options.
1. see the product wise brand (using more options)
2. see the brand wise product (using more options) 

Active Window is exist  but scr_model is not exist any more so that more options is right now disable. 

**Expected behavior**

Add a new src_model attribute on active window (.xml file) for see the product wise brands and brand wise products.

so that the more options will enable for product brand and product model.

**source:**
https://apps.odoo.com/web/login?redirect=/loempia/download/product_brand/8.0.0.1.0/6jQofx0RPRonf60kvPkAP5.zip?deps

**Comment by pedrobaeza** [comment]
As this a feature request and nobody has made a PR, I close.
