### ISSUE TITLE
Product_Brand not installable on v9c

### ISSUE THREAD

**Issue by KaloyanNaumov** [OCA/product-attribute#178]
There is a bug preventing product_brand to be installed. Funny part is that I saw it installing in some cases, but in general, it's failing. Both on fresh DB and on a DB with other modules.

The error is:
`
..... exception stack trace upper part ....

```
  File "/Users/kani/odoo/odoo/openerp/models.py", line 1271, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Error details:
View inheritance may not use attribute 'string' as a selector.

Error context:
View `product.search.form`
[view_id: 991, xml_id: n/a, model: product.product, parent_id: 280]
None" while parsing /Users/kani/odoo/OCA-addons/product_brand/product_brand_view.xml:132, near
<record id="product_search_form_view" model="ir.ui.view">
            <field name="name">product.search.form</field>
            <field name="model">product.product</field>
            <field name="inherit_id" ref="product.product_search_form_view"/>
            <field name="arch" type="xml">
                <data><field name="categ_id" position="after">
                    <field name="product_brand_id"/>
                </field>
                <group string="Group by..." position="inside">
                    <filter string="Brand" name="groupby_brand" domain="[]" context="{'group_by' : 'product_brand_id'}"/>
                </group>
            </data></field>
        </record>

```

**Comment by pedrobaeza** [comment]
You are not using the updated 9.0 version. Please check.

**Comment by lukebranch** [comment]
This is due to the fact the version you've installed on 9.0c is written for 8.0.

Take a look at the version in the 9.0 branch.

**Comment by KaloyanNaumov** [comment]
You are right, I wasn't using the latest for some (strange) reason. And the PR is merged long ago.

Please excuse me!

**Comment by KaloyanNaumov** [comment]
Guys, I found out why it happened.

There is a faulty version in the AppStore, 
https://www.odoo.com/apps/modules/9.0/product_brand/

that comes from the SerpentCS repo:
https://github.com/JayVora-SerpentCS/SerpentCS_Contributions-v8#9.0

And Odoo's AutoUpdate feature overwritten the one from the OCA branch. 
As per Odoo, it's: `Update Product Brand Manager 9.0.0.1 (9.0.1.0.0)`

Better be fixed from the App Store's offering.
