### ISSUE TITLE
Routes not showing up in profile

### ISSUE THREAD

**Issue by Nkburdick** [OCA/product-attribute#183]
module: product_profile
version: 1.0
branch 8.0

**Steps to reproduce**
- With the fields for profile_default_route_ids incorporated into the code, no routes are showing up on the product profile screen.  Here's the code I have in my product.py for the product_profile_example module (which I modified)

`
from openerp import models, fields

class ProductProfile(models.Model):
    _inherit = 'product.profile'

```
def _get_types(self):
    return [('product', 'Stockable Product'),
            ('consu', 'Consumable'),
            ('service', 'Service')]

profile_default_categ_id = fields.Many2one(
    'product.category',
    string='Default category')
profile_default_is_landed_ok = fields.Boolean(
    string='Landed Cost Product?')    
profile_default_sale_ok = fields.Boolean(
    string='Can be Sold',
    help="Specify if the product can be selected in a sales order line.")
profile_default_hr_expense_ok = fields.Boolean(
    string='Can be Expensed',
    help="Specify if the product can be selected in an expense report.")
profile_default_purchase_ok = fields.Boolean(
    string='Can be Purchased')
profile_default_route_ids = fields.Many2many(
    'stock.location.route',
    domain="[('product_selectable', '=', True)]",
    widget="many2many_checkboxes",
    string='Routes',
    help="Depending on the modules installed, this will allow "
         "you to define the route of the product: "
         "whether it will be bought, manufactured, MTO/MTS,...")
profile_default_uom_id = fields.Many2one(
    'product.uom',
    string='Unit of Measure')
cost_method = fields.Selection(
    string='Costing Method',
    selection=[('standard', 'Standard Price'), ('average', 'Average Price'), ('real', 'Real Price')])
profile_default_standard_price = fields.Float(
    string='Cost Price')
valuation = fields.Selection(
    string='Inventory Valuation',
    selection=[('manual_periodic', 'Periodical (manual)'),('real_time', 'Real Time (automated)')])
`
```

**Current behavior**
The profile_default_route_ids doesn't cause the routes to be selectable in the product profiles screen.  Shown in this screenshot:
![product_profiles_-_odoo](https://cloud.githubusercontent.com/assets/381289/19134466/0be5eb6a-8b13-11e6-8a88-f5720c34f1d8.jpg)

But the routes are definitely selectable on the new product screen.  Shown here:
![products_-_odoo](https://cloud.githubusercontent.com/assets/381289/19134491/2cd3c45a-8b13-11e6-9bb8-f1881d81c3d8.jpg)

Am I missing something?
Thanks!!!

**Comment by bealdav** [comment]
Hi Nick

You're right, default behavior without defined form view, is to not display relational fields m2m and o2m.

But it save a lot of time avoiding to build this form. 
Personally, I don't use UI to define my profiles but xml data. Then profile_default_route_ids field is available, but yes invisible.
It's a missing part in the documentation in known limitations you're right

Second solution is to build yourself your own form view for the profiles.

Third solution (the best) is surely to add these fields (if existing) dynamically after this line:
https://github.com/OCA/product-attribute/blob/60a7df7104f1ab3df44b1374f082a6a67dd7b990/product_profile/product.py#L105

I would appreciate if you could make a PR on product-attribute repository to fix it.

Use pdb at this line, then it should be easy.

Let me know, if there is a difficulty.

Thanks a lot to use this module

**Comment by pedrobaeza** [comment]
Is this solved?

**Comment by bealdav** [comment]
No and no feedback of @Nkburdick

**Comment by pedrobaeza** [comment]
Should we close it?

**Comment by bealdav** [comment]
if no answer of @Nkburdick  in few days, yes

**Comment by ovnicraft** [comment]
Close it please @pedrobaeza
