### ISSUE TITLE
[10.0] RFC: product_customer_barcode (extend product_customer_code to include customer barcodes)

### ISSUE THREAD

**Issue by lukebranch** [OCA/product-attribute#197]
@pedrobaeza ,

I'm planning on creating a new module for my own use and would like to know if a PR would be accepted to the OCA for an extension on the product_customer_code module to add customer barcodes in multiple formats.

The extra fields added to extend product_customer code would be:

<ul>
<li>barcode type/format (eg. EAN13, UPC-A, etc.)</li>
<li>barcode value (eg. EAN13 code)</li>
<li>customer product name (eg. this is used when customers require use of their own product name or language to describe the product.)</li>
</ul>

Before I start writing it i'd like to know if the OCA has any use for this module, and whether any additional features/fields should be added, and which repository I should target before a PR is made.

For these features I would assume I should create one module purely for the barcode features, and one module for the customer's product name, for example:

product_customer_barcode
product_customer_name

**Comment by pedrobaeza** [comment]
Look at https://github.com/OCA/stock-logistics-barcode/pull/49

**Comment by pedrobaeza** [comment]
and https://github.com/OCA/stock-logistics-barcode/pull/32

**Comment by lukebranch** [comment]
@pedrobaeza ,

thanks for the suggestions, i've taken a quick look at those PR's.

The scope of my proposed module was simply to allow the storage of a customer's barcode numbers (ie. just the value), and allow for a secondary field to specify which barcode format is being used. 

This is useful for manufacturers and distributors that might be required to store a record of customer's own barcode numbers, and product names in the same way that product_customer_code (Vauxoo's module) allows the storage of a customer's product code/sku.

For my use case this module would then be used to allow for easy creation of custom reports for printing of the customer's own barcode labels using these values.

Do you suggest I expand the scope of the modules to allow for the generation of customer-specific product barcodes based on the work being done in these PR's?:

https://github.com/OCA/stock-logistics-barcode/pull/49
https://github.com/OCA/stock-logistics-barcode/pull/32

**Comment by pedrobaeza** [comment]
Well, I don't have a strong opinion then about how to proceed. Any other thought, @legalsylvain or @gurneyalex ?

**Comment by legalsylvain** [comment]
Hi @lukebranch,

> The scope of my proposed module was simply to allow the storage of a customer's barcode numbers (ie. just the value)

I can not figure out this need. base module provides on 'res.partner' a 'barcode' field. (that is displayed only if point of sale module is installed, but it's a bad design in Odoo Core I think)
https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/res/res_partner.py#L205

> , and allow for a secondary field to specify which barcode format is being used. 

Well, OCA/stock-logistics-barcode#49 provides barcode_rule_id field that allows your to mention which pattern you want to use for your customer.

In a few words, I think that installing barcodes_generator_partner could provides the feature you're needing. 

I took a look on product_customer_code module. It is available only for version 7.0 and this module seems to provide product code for customers, that is not exactly the same thing.

Kind regards.

**Comment by lukebranch** [comment]
Hi @legalsylvain ,

Thanks for the comments. In many manufacturing/trading companies in Hong Kong it is necessary to store a record of the company's own internal reference/sku as well as the customer's (at least in our case it is).

For example if I am manufacturing a product on behalf of a customer under their own brand, using their own product packaging, etc. it is necessary to also store and print customer SKU, barcodes and product names (these may be in different languages as well). These customer references may also need to be included on Sale Orders and other documents.

It is definitely a need for our company, and I believe since Vauxoo has originally built something to do the same for the customer code/SKU I believe we are not the only ones that could benefit from this module.

I will take a look at barcodes_generator_partner as well as https://github.com/OCA/stock-logistics-barcode/pull/49 to see if I can achieve what i'm looking to do without building an extension to product_customer_code. If not I may come back and submit a PR for each of the modules (including a port of product_customer_code) for the 10.0 branch.

**Comment by legalsylvain** [comment]
OK. Thanks. I so close this issue for the time being. please feel free to reopen it when you'll have an analysis on the two PR.
kind regards.

**Comment by lukebranch** [comment]
ok, thanks.
