### ISSUE TITLE
product_size module - Note for porting

### ISSUE THREAD

**Issue by gdgellatly** [OCA/product-attribute#210]
length field will require renaming as per underscore.js bug now linted in mqt.

**Comment by gdgellatly** [comment]
actually this applies to product_dimension as well - do we really need both modules anyway?

**Comment by leemannd** [comment]
@gdgellatly Hello, product_size was used/ported only till V7. IMHO it could be removed in the V10.

**Comment by pedrobaeza** [comment]
Pylint now has a check for this case, so I close.
