### ISSUE TITLE
RFC: Product features

### ISSUE THREAD

**Issue by rubencabrera** [OCA/product-attribute#215]
From a client's request, I'm working on a module to add product features in a particular way:

+ Features and products have a M2M relation.
+ If a template has a feature, all products inherit with exactly the same value. 
+ A feature has an image and an alt text. 

I've seen a similar development somewhere but can't find it now, so I'm starting from scratch, defining a new model. 

Is this the right repo to make a PR when I'm done? Should I use some existing model? Product attributes don't fit the purpose, because all variants have the same features as the template. Product categories could do the deed, but they are not meant for this purpose and using them seems confusing.

**Comment by pedrobaeza** [comment]
Why don't you use product_multi_image?

**Comment by lukebranch** [comment]
@rubencabrera ,

Maybe i'm mistaken, but I think the module you're referring to is product_custom_info:

https://github.com/OCA/product-attribute/tree/8.0/product_custom_info

I'm not sure if it covers your exact requirements, however it might be a good start.

I've done a quick and dirty port to version 9.0 and 10.0 for that module and base_custom_info, and can share the code (mostly just view changes and some minor code tweaks to make it compatible with the new API) if it's helpful.

Regarding having an image connected to the feature, I can see how this might be useful (eg. icon representing the feature for display in your website layout), however perhaps product_custom_info could be extended to match your requirements.

**Comment by pedrobaeza** [comment]
product_custom_info is already migrated to 9.0: https://github.com/OCA/product-attribute/pull/177

**Comment by rubencabrera** [comment]
@pedrobaeza I'm already using product_multi_image, but images don't add information about the extra feature.

On the other hand, as @lukebranch said, product_custom_info seems to be on the right track. The only problem is that the user has to manually set a value for the custom property on each product template. Maybe this feature is way too simple for the functionality this module provides. 

I'm using a very similar module previously developed and adapting it to a more general use case hoping it's useful for someone else.

**Comment by lasley** [comment]
@rubencabrera Will the existing product attributes not work? Seems like we're just talking about a Product Template <=> Variant relationship, right? Or are you proposing to apply these attributes at the variant level?

**Comment by rubencabrera** [comment]
Hi @lasley. Features are set at template level and they are common to every variant. Attributes generate combinations where each variant has only one set of values and the rest are excluded. You can check hte PR #216 to see it.

**Comment by pedrobaeza** [comment]
Closing as there's a PR.
