### ISSUE TITLE
[RFC] Restrict Products to Company

### ISSUE THREAD

**Issue by lasley** [OCA/product-attribute#217]
This module will allow for the assigning of products to specific companies, which doesn't look to be a thing at the moment. There is a `company_id` on product, but I don't see it actually doing anything.

With that in mind, this module will add a `restrict_company_ids` to `product.template`. It will default to all companies that exist, in order to not change the operation of existing products.

An ACL will be added to restrict products a user can see, based on their `company_id` against the `restrict_company_ids`.

Plan seems simple enough, I'm just wondering if anything like this exists already. I feel like this is a problem that anyone using multi-company would be experiencing, so I think maybe I'm missing something.

**Comment by pedrobaeza** [comment]
Please look at https://github.com/OCA/multi-company/pull/34 :wink:

**Comment by pedrobaeza** [comment]
I'm repairing .travis.yml for having global matrix for activating runbot in that repo.

**Comment by lasley** [comment]
Oh well look-y there. Thanks @pedrobaeza!
