### ISSUE TITLE
sql constraint stays upon uninstallation unique default code

### ISSUE THREAD

**Issue by farazbdm** [OCA/product-attribute#219]
module: product_sequence
version: 8.0

**Steps to reproduce**
- Install Module
Uninstall Module

**Current behavior**
sql constraint of uniq default code is added to the product_product_default_code table upon installation.
this sql constraint doesn't gets removed upon uninstallation.

**Expected behavior**
Either module should work without sql constraint or else upon uninstallation the constraint should be removed.

**Comment by pedrobaeza** [comment]
Can you provide a PR with your solution?
