### ISSUE TITLE
product dimension not saved in record creation

### ISSUE THREAD

**Issue by mehdi-ghezal** [OCA/product-attribute#220]
**_module:_** product_dimension
**_version:_** 9.0

### Steps to reproduce

- Install module
- Create a new product template with dimension
- Save the product
- Check the dimension

### Current behavior

Product dimension are **not** saved for product template

### Expected behavior

Product dimension **should be** saved for product template

### Reason

Product template use related fields for dimension (width, height, ...) that are bind to product.product ; during record creation related field are not persist.

When update a record, everything work as expected.

**Comment by pedrobaeza** [comment]
@leemannd, can you check this issue?

**Comment by leemannd** [comment]
@pedrobaeza Yep. I'm going to check this in the end of the week, beginning of the next one.
EDIT: @pedrobaeza @mehdi-ghezal This [pr](https://github.com/OCA/product-attribute/pull/221/files) from @vrenaville should correct the behavior.
