### ISSUE TITLE
Q: product ean13 field?

### ISSUE THREAD

**Issue by simahawk** [OCA/product-attribute#226]
This field has been replaced in odoo with `barcode` but I need both since our customer has internal code (default code = barcode) and an external code (to be used in Prestashop and other external services) that should be just a valid ean13. 
Is there any module that add it back? I cannot find anything in this repo.
If no module is ready I can submit one here, if anyone is interested.

**Comment by lasley** [comment]
Hey @simahawk - Take a look at the [`barcodes_generator_product`](https://github.com/OCA/stock-logistics-barcode/tree/9.0/barcodes_generator_product). It doesn't fully meet your specs of using a different column, but it is insanely easy to add more logic to do so. You can use my [`barcodes_generator_package`](https://github.com/OCA/stock-logistics-barcode/pull/68) as an example of implementation on a non-existant col.

**Comment by lasley** [comment]
Also, have you thought about using the Internal Ref as the internal one, and barcode as external? You could then just implement the barcode generator side of things on the pre-existing column, instead of creating a new one.

**Comment by simahawk** [comment]
@lasley hey! :) thanks for the tips (and for noticing me about that cool feature) but that's too much work for just a - in our case - "stupid" char field, I think.

And, yes, we considered using barcode as external but it won't work because they need to scan and print using internal ref so barcode must be equal to ref. Unless you override all the barcode-scan machinery.... but, then, once again... I won't do all this work for an additional char field :)

So, ATM I solved the requirement w/ an additional field + small override of PS mapper to use this field instead of barcode.

**Comment by lasley** [comment]
I was under the impression that all barcode scanning happened against the barcode nomenclatures? As an example, [`barcodes_generator_partner`](https://github.com/OCA/stock-logistics-barcode/tree/9.0/barcodes_generator_partner) adds a new nomenclature type & a new barcode field to a model that didn't previously have it. This should mean that the client is scannable, assuming that the scanner is working against the core nomenclatures.

Admittedly I haven't screwed around with the core scanning interfaces (POS/Barcodes) - so this could be wrong. Seems a bit weird that Odoo SA would design all this intricacy without implementing it into their own interface though.

**Comment by simahawk** [comment]
@lasley hmm, maybe I am wrong but in a customer project we use enterprise version and the module "stock_barcode" searches products and pickings like this:
```
self.env['product.product'].search(['|', ('barcode', '=', barcode), ('default_code', '=', barcode)], limit=1)
```
so, `barcode` field is hardcoded :/ and I fear is the same for many other logics.

The real point is: are you telling me that I can use `https://github.com/OCA/stock-logistics-barcode/tree/9.0/stock_scanner` and all related modules to replace enterprise machinery for scanning pickings, products and so on? :) Sorry if it sounds as a dumb question but this is the 1st time I play w/ such things :stuck_out_tongue: 

If the answer is "yes" which is the minimal set of modules I should use to cover this basic need?

**Comment by lasley** [comment]
> and all related modules to replace enterprise machinery for scanning pickings, products and so on?

That's the goal, but the web part isn't done - OCA/stock-logistics-barcode#55

I don't have (or want) Enterprise, so I can't comment on how anything there works. Weird that Odoo SA didn't use their own nomenclature type definitions though. They totally relate back to model, and they even relate to the field once the generator modules come into play.

I'd say probably stick with your solution for the moment, but maybe think about helping out on the PR too 😉 .

**Comment by ovnicraft** [comment]
No updates here and Q as i read was solved, close it please.
