### ISSUE TITLE
[RFC] product_default_image: Default images by category

### ISSUE THREAD

**Issue by lasley** [OCA/product-attribute#227]
This is a fairly simple module that will provide a default image for products, similar to the partner avatars. This image will be configurable on both a global & a product category level.

A view will be added in the Product Configuration menu, which will allow for the configuration of the images and the categories.

The create method of `product.template` will be overridden. If the `image` key is not present, the default image will be generated based on category or global.

Anyone have any thoughts or pre-existing strategies/modules that we can base from?

**Comment by pedrobaeza** [comment]
Two notes:

* Default image for categories should be set on each category.
* Bring default image on default_get for the product.template model, not on write/create.

**Comment by lasley** [comment]
> Default image for categories should be set on each category.

Such as in the category form view, instead of a separate view? Yeah that's probably a better direction.

> Bring default image on default_get for the product.template model, not on write/create.

TIL `default_get`. Fully agree.

**Comment by pedrobaeza** [comment]
> Such as in the category form view, instead of a separate view? Yeah that's probably a better direction.

That's my idea, yes.

**Comment by lasley** [comment]
Closing to track in PR #243
