### ISSUE TITLE
`product_multi_image` broken if no image is on the template

### ISSUE THREAD

**Issue by simahawk** [OCA/product-attribute#228]
**Context:**
* v9
* template with no images, variant with no images

**Issue:**
If you add an image to a variant:
```
  File "/opt/odoo/external-src/product-attribute/product_multi_image/models/product_product.py", line 44, in _inverse_main_image_medium
    product._inverse_main_image(product.image_main_medium)
  File "/opt/odoo/src/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/external-src/product-attribute/product_multi_image/models/product_product.py", line 29, in _inverse_main_image
    product.image_ids[0].write({
  File "/opt/odoo/src/openerp/models.py", line 5756, in __getitem__
    return self._browse(self.env, (self._ids[key],))
IndexError: tuple index out of range
```
We miss a safe check here https://github.com/OCA/product-attribute/blob/9.0/product_multi_image/models/product_product.py#L28

**Comment by pedrobaeza** [comment]
Well, it's supposed that if you have an image, automatically gets the first image also on multi-images, so this is the part we have to check. Why don't you have this first image? Maybe some piece of code that makes it?

**Comment by simahawk** [comment]
hmm, I don't get this :)

It's pretty easy to replicate:

1. create a product template w/ variants
2. go to one of the variants
3. add an image
4. save => kabooom! :)

So, are we expecting to not be able to add images to variants IF the template has no image? If yes, we should make variant field readonly, otherwise we need to fix that method to write on image_ids only if there's something there or to add a new image if none.

**Comment by pedrobaeza** [comment]
Uhm, let me check then. The initial idea is:

* When you add an image on a variant, that image is registered also on the template, but with only that variant allowed.
* When you add an image on the template, all variants get this image, and no variant restriction is applied.
* From template, you can change the variants that are going to use this image.
* From a variant, if you upload again an existing image, it's matched and the existing image adds the variant as allowed to see that image.

In this logic, that was made for v8, I don't know if something has changed in the port to v9.

**Comment by simahawk** [comment]
That makes sense, the problem is that it's broken because it [tries to write on `product.image_ids[0]`](https://github.com/OCA/product-attribute/blob/9.0/product_multi_image/models/product_product.py#L27) only because `image` is valued. Adding a new image is not taken into account at all.

**Comment by simahawk** [comment]
@pedrobaeza this is what I mean ;)
https://github.com/OCA/product-attribute/pull/229/files

**Comment by lasley** [comment]
@simahawk - Can this be closed now?

**Comment by simahawk** [comment]
yup!
