### ISSUE TITLE
[RFC] Breakup/Reorg of product-attribute repo

### ISSUE THREAD

**Issue by gdgellatly** [OCA/product-attribute#256]
Hi all,

Since v8 I've found this repo has become a combination of concepts.  It's initial conception was for adding additional attributes (as in fields) to products, but with v8 and the renaming of dimensions to attributes it was the effective obsolescence of product_variant_multi and therefore the product-variant repo. 

I've been working hard to supplement the old features of product_variant_multi a module I've been very active in since v5 and modernise to the current variants way of doing things.  

Plus I've been modernising and open sourcing a lot of old internal code that deals with variants and still more to come giving OCA what I think are some pretty awesome variant features.

I propose that we move those modules which deal just with the control, management and enhancement of variants and variant creation into the product-variant repo.

As a minimum I'd expect this to include (with current PR's)
product_combination_exclude #255 
product_attribute_group #254 
product_code_builder #244, #204 
product_attribute_priority #244, #204 
product_attribute_multi_type (I don't know much of this module)

arguably product_price_on_variant although IMO might be time to remove this module as it's pretty well handled now in other ways.

In addition I'm working on a few other modules, such as the establishment of a product_manager role which manages products and reorganizes related menus, variant pricing manager and an all encompassing app which basically installs most of these modules for organizations that need serious variant management.

expected interested parties
@pedrobaeza chief reviewer :) and variant work in odoomrp 
@jgrandguillaume PSC

Akretion Team - longtime pvm contributors
@bealdav 
@alexis-via
@rvalyi
@bguillot 

@lmignon current PR's

Apologies to anyone I've missed, or anyone who doesn't want to know and has been included.

**Comment by pedrobaeza** [comment]
All the variant/attribute stuff should be in OCA/product-variant IMO.

**Comment by gdgellatly** [comment]
This is done I think
