### ISSUE TITLE
[8.0/Master] Any plans on porting product_customer_code to 8.0 soon?

### ISSUE THREAD

**Issue by lukebranch** [OCA/product-attribute#28]
I've been working on building a module to achieve the functionality of product_customer_code, however I have just come across this module and it looks like it achieves what I aimed to achieve with my own module. 

I'd like to know if there is any roadmap for porting this particular module to 8.0 as if there are plans to port it soon I will wait until the module is ported to 8.0 according to OCA standards.

If there are no plans from OCA to port the module in the near future I will begin work on porting the module to 8.0 myself and would be happy to submit pull requests once i'm done if community involvement outside OCA is wanted. If this is the case is there anywhere I can find a list of OCA requirements for submission so that I can try to match these requirements before submitting pull requests?

**Comment by acysos** [comment]
Hello,

I also need it. I'm working in it.

Greetings

**Comment by lukebranch** [comment]
@acysos ,

It's great to know you're working on it. I've watched your repository so that I receive updates on changes:

https://github.com/acysos/product-attribute

Please let me know if there's anything I can contribute.

**Comment by lukebranch** [comment]
@acysos ,

Just an FYI - This module seems to install without any issues in 8.0. I'm not sure whether the full functionality is present in 8.0 in it's current state as I have not yet tested the module extensively, however a tab called 'Customer Code' has been added to variants (product.product) and is visible and functioning on variants.

**Comment by acysos** [comment]
Yes, I know. I have migrated the module to the new API, I made some tests and it works. I have other PR in this repository, when it is solved I request another PR with this module.

If you need it now, I can send you by email.

Greetings

**Comment by pedrobaeza** [comment]
Ignacio, you can make PRs in paralell if you want. You only need to create another local branch out of the current one, add the module, and push to a new remote branch.

**Comment by lukebranch** [comment]
@acysos ,

Thanks for letting me know, and good to hear it's almost ready for pushing to the OCA repository. If you could email your migrated version I would really appreciate it. My email is:

odoocommunitywidgets (at) gmail.com

i'm currently building a module for showing product_code (among other things) on order lines in printed reports (WIP):

https://github.com/OdooCommunityWidgets/product_extended_report_order_lines

so it would be useful to have the most up to date code to work with.

Thanks!

**Comment by lukebranch** [comment]
@acysos ,

Just a quick question regarding the module, is it the intended functionality to have this module work only on product variants, but not on product.template?

**Comment by acysos** [comment]
Hello,

I have made a PR: https://github.com/OCA/product-attribute/pull/38

I have to make some changes, but it works in product.template

Greetings

**Comment by lukebranch** [comment]
@acysos ,

Thanks! I'll clone #38 for now and wait for OCA to merge this into the 8.0 branch.

**Comment by lukebranch** [comment]
@acysos ,

I've been using your fork of product-attribute/product_customer_code (unfinished as far as I can tell), however i've run into an issue that I think may be related to the module.

The issue is detailed here:

https://github.com/odoo/odoo/issues/5241

however i'd like to confirm that it is indeed product_customer_code and note the Odoo core or another community module.

Thanks for your awesome work so far, i've noticed some very useful features, including being able to search for customer product codes using the website_sale search among other things.

Do you have an estimate on a roadmap for completion for this module at this point in time?

**Comment by acysos** [comment]
hello, 

I expect to solve it the next week.

Greetings

**Comment by lukebranch** [comment]
@acysos ,

Thank you! That's great news.

**Comment by renatonlima** [comment]
Hello @acysos, any news about product_customer_code migration? we have usable in https://github.com/akretion/product-attribute, I saw you did something https://github.com/acysos/product-attribute can you do a PR? I can help in review.

**Comment by renatonlima** [comment]
I found this https://github.com/OCA/product-attribute/pull/122

**Comment by acysos** [comment]
Hello,

See https://github.com/OCA/product-attribute/pull/122

Greetings

**Comment by pedrobaeza** [comment]
The migration is on progress on https://github.com/OCA/product-attribute/pull/122, so we can track it there, so I close.
