### ISSUE TITLE
[RFC] Product Customer Code

### ISSUE THREAD

**Issue by elicoidal** [OCA/product-attribute#296]
Is there any equivalent to https://github.com/OCA/product-attribute/tree/7.0/product_customer_code
in v10/11?

If not we could create a migration of the existing one (or some similar concept)
@pedrobaeza @sebastienbeau

**Comment by eLBati** [comment]
Hi @elicoidal see https://github.com/OCA/product-attribute/pull/236 and https://github.com/OCA/product-attribute/pull/292

**Comment by elicoidal** [comment]
thanks @eLBati 
Answered=>closing
I will review the PR and test
