### ISSUE TITLE
[RFC][10.0]pricelists based on vendor/customer price

### ISSUE THREAD

**Issue by AaronHForgeFlow** [OCA/product-attribute#297]
In Odoo8 it was possible to create pricelist based on the supplier info in the product form. That was used to import the prices in the product form to the SO line. From V9 onwards that option is not available in the pricelist.

The module [product_supplier_info_for_customer](https://github.com/OCA/product-attribute/pull/292) extends the supplier.info model to be used also for customers. Then, when there's a SO for that customer and a SO line for that supplier, the system fetched the price from the supplierinfo table.

I'm considering to add back the option in the pricelist, so we can choose a price based on the supplier info in the product form. What do you think about this?

PS:  In case this feature is not added back, product_supplier_info_for_customer should be deprecated in favor of product_customer_code. This was already discussed here: https://github.com/OCA/product-attribute/pull/236 and the conclusion was to migrate product_supplier_info_for_customer.

**Comment by pedrobaeza** [comment]
product_supplier_info_for_customer indeed can add that option for having another way of defining the pricelists. It can even have at partner level the inverse table putting all the products with their prices.

**Comment by tgoetten** [comment]
I would love to get the option back to calculate prices based on vendor (supplier) prices from the inventory (v10) / purchase (v11) table.

**Comment by AaronHForgeFlow** [comment]
Perhaps https://github.com/OCA/product-attribute/pull/400 is what you need @tgoetten.

BTW That PR was already merged so I will close this Issue. For additional requirements please create another issue.
