### ISSUE TITLE
[11.0] product_end_of_life

### ISSUE THREAD

**Issue by max3903** [OCA/product-attribute#319]
This module allows you to set the End of Life Date of a Product.

Products with EoL Date in the past are excluded from the list of Products in Purchase Order so the product can not be ordered.

A scheduled action is created to know in advance the list of products whose EoL Date is approaching.
An email will be sent to the members of the Discussion Channel for Product Eol Notification Group.

# Configuration

## Discuss Channel

* Look for the the Private Channel -> Product End-Of-Life Channel.
* Click settings and add members on this channel.

## Scheduled Action

* Go to Settings > Technical > Automation > Scheduled Actions
* Look for Product: End-Of-Life Notification
* Set desired values. Run manually to test.
* Check email is sent out to the members of the Product End-Of-Life Channel.

# Usage

## Products

* Go to Inventory > Master Data > Products
* Create or edit a product
* Enter the End of Life Date and save

**Comment by max3903** [comment]
In a second version of the module, implement @simahawk suggestions to improve the approaching_** fields handling (See details in #328).

**Comment by bodedra** [comment]
Ready to close in favour of https://github.com/OCA/product-attribute/pull/328/
