### ISSUE TITLE
product_sequence, unique code not working in odo10 enterprise

### ISSUE THREAD

**Issue by diezcode** [OCA/product-attribute#330]
module: product_sequence
version: 10.0 enterprise

**Steps to reproduce**
Install Module
Uninstall Module

**Current behavior**
Can duplicate product and can save product with same default_code as other products.

**Expected behavior**
Should not let you save a product with an **existing default_code**

**Comment by ovnicraft** [comment]
I cant reproduce your issue, tested with latest rev.

Longer time here, close it please.
