### ISSUE TITLE
product_internal_reference_unique & product_internal_reference_mandatory

### ISSUE THREAD

**Issue by max3903** [OCA/product-attribute#331]
# product_internal_reference_unique 

This module adds a constraint on the internal reference of the product to make it unique across the database.

# product_internal_reference_mandatory

This module adds a constraint on the internal reference of the product to make it mandatory.

**Comment by max3903** [comment]
Ping @agyamuta

**Comment by bodedra** [comment]
In favour of #333 and #334 , we can close these.
