### ISSUE TITLE
Product Index Migration

### ISSUE THREAD

**Issue by JonathanNEMRY** [OCA/product-attribute#342]
Hello!
I found the module product_index into this repo but it seems that is was completely forgotten?
Is there another way to index all product price into Odoo?

Many thanks,

-jne

cc @pedrobaeza

**Comment by pedrobaeza** [comment]
It has been not migrated as it was considered not useful for people. Right now, current indexes are good for most production DBs. If not, changes are done on Postgres/custom modules.
