### ISSUE TITLE
[11.0] Product Brand Manager

### ISSUE THREAD

**Issue by Joaco1980** [OCA/product-attribute#346]
The dimensions of the brand logos in the Kanban view do not fit
![captura](https://user-images.githubusercontent.com/14363121/38570522-5592748e-3cee-11e8-9670-9c913266473c.jpg)

**Comment by pedrobaeza** [comment]
This is because there's no max-size defined in the kanban view. Please make a PR adjusting it.

**Comment by rousseldenis** [comment]
Fixed by https://github.com/OCA/product-attribute/pull/364
