### ISSUE TITLE
[11.0] product_brand logo not showing up in kanban view

### ISSUE THREAD

**Issue by wrhansen** [OCA/product-attribute#354]
The kanban view of the product_brand page, found by visiting `Sales > Configuration > Product Brands`, is not displaying the brand `logo`. Instead you see the broken image icon.

Here's a screenshot of what it looks like:

![broken-image](https://user-images.githubusercontent.com/1350065/40733635-1f5741aa-6404-11e8-8012-d34b5a7510a8.png)

The odoo backend raises the following error for each image it tries to fetch:

```
ValueError: invalid literal for int() with base 10: '3,033'
```

Right away the comma (in *3,033*) spelled out an issue with the values that were being passed to the image url. So, doing some further investigation I tracked down the issue to the arguments passed to the image url. Here's the outstanding code (from [product-attribute/product_brand/views/product_brand_view.xml](https://github.com/OCA/product-attribute/blob/11.0/product_brand/views/product_brand_view.xml)).
From the record with id `view_product_brand_kanban`:

```
<img t-att-src="kanban_image('product.brand', 'logo', record.id.value)"
```

The outstanding error here is the use of `record.id.value`. This is returning the id as a formatted integer. 
 (ex 3,033 instead of 3033). Instead, if you use `record.id.raw_value`, the issue is fixed.

Pull request coming shortly

**Comment by pedrobaeza** [comment]
Great, waiting for the PR! Next time, it's better to do the PR directly and include the issue report in it.
