### ISSUE TITLE
product_pricelist_fixed_price failing tests

### ISSUE THREAD

**Issue by daramousk** [OCA/product-attribute#381]
On 0d09b6e2 and specifically on product_pricelist_fixed_price/tests/test_product_pricelist_fixed_price.py:45 there seems to be an attempt to set the `product.pricelist` type to `purchase` which fails because the `purchase` type is inserted on the `odoo.addons.purchase` module and `product_pricelist_fixed_price` does not depend on it.

Is this a bug as I understand?

**Comment by pedrobaeza** [comment]
Yes, it seems so
