### ISSUE TITLE
[V11]product_supplierinfo_for_customer

### ISSUE THREAD

**Issue by MiguelMachadoM** [OCA/product-attribute#402]
I Dont know if a error or not or this changed in V11.

The problem:
If I create a Price List with 2 elements
Element 1: Formula with Partner Prices on the product form
Element 2: Other Price List

I expected that if not found the price of this product for this customer go to the next element based on another Pricelist. 

But instead get default sale price of product from on information tab.

Before this worked, and I remember that there was a sequence number.

thats the question.

![imagen](https://user-images.githubusercontent.com/7348561/47951854-f4b59800-df66-11e8-8859-5d6d742bb442.png)

___________________________________________________
No se si es un bug o el funcionamiento de Odoo cambia en la V11 (yo tenia un modulo que me hiciste que hacia esto)

El problema que tengo es que cuando creo una tarifa con los precios fijos por clientes (es decir los que están en la ficha de producto) y luego agrego la otro elemento con precios de otra trarifa de donde tiene que tirar del resto de precios, no busca los precios en esa tarifa si no que trae los precios de que estan en la ficha del producto(Precios de venta en Informacion General)

Antes las tarifas tenian una secuencia, y le dabas prioridad a cada elemento, esto ya no es así.

Por eso la pregunta.

**Comment by pedrobaeza** [comment]
Sorry, this issue tracker is only in English because it has a wider audience. Any way, I haven't migrated that module and can't say about it.

**Comment by MiguelMachadoM** [comment]
@pedrobaeza  Translated

**Comment by pedrobaeza** [comment]
I have removed my name as this issue tracker is not for me, but for whole OCA. Anyone knowing about it might answer, but not guaranteed.

**Comment by pedrobaeza** [comment]
You have opened a new issue, so closing again.
