### ISSUE TITLE
[V11] product_supplierinfo_for_customer

### ISSUE THREAD

**Issue by MiguelMachadoM** [OCA/product-attribute#403]
@sergio-teruel  @mreficent 
Hello
I Dont know if a error or not or this changed in V11.

The problem:
If I create a Price List with 2 elements
Element 1: Formula with Partner Prices on the product form
Element 2: Other Price List

I expected that if not found the price of this product for this customer go to the next element based on another Pricelist. 

But instead get default sale price of product from on information tab.

Before this worked, and I remember that there was a sequence number.

thats the question.

![imagen](https://user-images.githubusercontent.com/7348561/47951854-f4b59800-df66-11e8-8859-5d6d742bb442.png)

___________________________________________________

**Comment by MiquelRForgeFlow** [comment]
If not exist a product price for the partner pricelist, then the standard price will be taken, it won't go to the next element. I think your problem can be solved by creating another pricelist or putting a product price for that partner. But if you don't want this behavior, feel free to collaborate :)
