### ISSUE TITLE
Delete branch

### ISSUE THREAD

**Issue by rousseldenis** [OCA/product-attribute#425]
@rafaelbn Could you please delete your custom branch on OCA side in this repo? Thanks

**Comment by pedrobaeza** [comment]
There's #405 with this branch. It was done through GitHub interface, which do this dirty things. Let's finish the PR for removing it.

**Comment by rafaelbn** [comment]
I have closed https://github.com/OCA/product-attribute/pull/405

I wish someone fix the readme or the module :smile:

**Comment by rafaelbn** [comment]
You can close issue :smile:
