### ISSUE TITLE
[12.0] product_supplierinfo_for_customer

### ISSUE THREAD

**Issue by hugho-ad** [OCA/product-attribute#454]
As Described at https://github.com/OCA/sale-workflow/issues/737, this module has some  inconsistencies of behavior across all the version down

I would like to migrate it to v12.0 so please let me your comments.

My notes:
- This module should move the domain at name field on `product.supplierinfor` to the model view, in order to search customers on the name field when trying to add a record on Customer section
https://github.com/odoo/odoo/blob/ab1bd93dde170afbfae24f68c8e39012295197f1/addons/product/models/product.py#L610

```xml
Customer view for sale section on Product From
<field name="name" domain="[('customer', '=', true)]"/>

Supplier view for purchase section on Product From
<field name="name" domain="[('supplier', '=', true)]"/>
```

**Comment by hugho-ad** [comment]
cc: @pedrobaeza , @rafaelbn , @moylop260

**Comment by hugho-ad** [comment]
FYI https://github.com/Vauxoo/product-attribute/pull/11

**Comment by rafaelbn** [comment]
This is already migrated here @hugho-ad https://github.com/OCA/product-attribute/pull/446 Maybe you can review
