### ISSUE TITLE
Pypi information out of date

### ISSUE THREAD

**Issue by enricostano** [OCA/product-attribute#478]
The Pypi [package](https://pypi.org/project/odoo11-addon-product-pricelist-supplierinfo/) for `product-pricelist-supplierinfo` has some information that is wrong or out of date.

 - Homepage points to https://github.com/OCA/sale-workflow instead of this repo
 - Statistics are related to the wrong repo. I guess related tothe previous point

This issue makes it difficult to find the source code from the Python package, although at the bottom of the description page it correctly points to this repo... I guess because it's just the `README.rst`.

In any case, thanks for maintaining Python packages in Pypi, we found them really useful! :heart_eyes:

**Comment by pedrobaeza** [comment]
Fixed in c4d82fbdb88e2419884b03a5e2d477d09a685a46.

Will be propagated to PyPi soon.

**Comment by enricostano** [comment]
Cool, thanks! Now that I know where to look at I will open a PR next time.
