### ISSUE TITLE
Clicking "Test Import" adds sequence numbers and leads to wrong sequences

### ISSUE THREAD

**Issue by geniustaha** [OCA/product-attribute#487]
Bug:
When we are importing products in bulk, if we click on the button test import, it updates the sequence numbers. (Even if we dont upload the sheet.)
How to reproduce:
1. Go to product Import.
2. Upload the sheet.
3. Click on Test Import Button.

Suppose there were 10 products of a certain category, the sequence number jumps by 10. Suppose there were 4 products, it jumps by 4.
Suppose if we press the test import twice, the sequence jumps by double the numbers.

We need a mechanism to detect test imports and not to make the next sequence number update when the test import button is pressed.

**Comment by pedrobaeza** [comment]
Module? Version?

**Comment by geniustaha** [comment]
**Sorry. I clicked the link and was directed to this page:**
https://apps.odoo.com/apps/modules/11.0/product_sequence/#bug-tracker
Module: Product Sequence
Version: 11

**Comment by pedrobaeza** [comment]
OK, understood, but this is not a problem of the module, but Odoo not unrolling that in their test import feature.

**Comment by geniustaha** [comment]
Ok sir. Understood.
Can you please guide how I can detect if Test import is clicked or import. I can add that to differentiate. 
Also, if you can guide on how to unroll that sequence number, that will be great.
Thanks.

**Comment by pedrobaeza** [comment]
No clue. I think you should add an issue on odoo/odoo about that.

**Comment by geniustaha** [comment]
Done:
https://github.com/odoo/odoo/issues/33950
