### ISSUE TITLE
product_sequence not compatible to be use with product variant.

### ISSUE THREAD

**Issue by Complexart** [OCA/product-attribute#492]
module: product_sequence
version: 8.0

**Steps to reproduce**
- after creating product template, adding variant will lead to:

     Constraint Error,The reference must be unique

**Current behavior**

**Expected behavior** product variant should be added and product code should update to work with the product variant code builder. eg. Pr00015CDA

**Comment by zm14** [comment]
Any news on this? 
It will be great if it works with product variants.
