### ISSUE TITLE
[10.0] [product_supplierinfo_for_customer] Typo and wrong value in context

### ISSUE THREAD

**Issue by joergfederspiel** [OCA/product-attribute#503]
In module "product_supplierinfo_for_customer" there is a typo and a wrong value in context for menu "Partner Pricelists"

Original code from product_view.xml:

```xml
<record id="product.product_supplierinfo_type_action" model="ir.actions.act_window">
    <field name="name">Partner Pricelists</field>
    <field name="res_model">product.supplierinfo</field>
    <field name="context">{'default_search_type':'supplier','default_type':'supplier','default_product_tmpl_id':id,visible_product_tmpl_id':False}</field>
    <field name="domain">[('type','=','supplier')]</field>
</record>
```

Should look like this:

```xml
<record id="product.product_supplierinfo_type_action" model="ir.actions.act_window">
    <field name="name">Partner Pricelists</field>
    <field name="res_model">product.supplierinfo</field>
    <field name="context">{'default_search_type':'supplier','default_type':'supplier','visible_product_tmpl_id':False}</field>
    <field name="domain">[('type','=','supplier')]</field>
</record>
```

**Comment by pedrobaeza** [comment]
What is the typo? Why current id to be put on product_tmpl_id is a problem?

**Comment by joergfederspiel** [comment]
The typo is the missing apostrophe before "visible_product_tmpl_id':False".

With the entry "default_product_tmpl_id':id" get the following error message when calling the view from menu "Partner Pricelists" in Purchases.
Where does the ID come from when calling the list view?

![Error - Partner Pricelist - Purchases](https://user-images.githubusercontent.com/4254810/65222584-b3b36d00-dabf-11e9-8eae-8f03bebed8c2.png)

**Comment by pedrobaeza** [comment]
OK, I see. Please make a PR fixing both things
