### ISSUE TITLE
[RFC] Product Documentation 

### ISSUE THREAD

**Issue by dreispt** [OCA/product-attribute#506]
The goal is to add the matching product documentation when a quotation is send by email. The documentation (PDF) files should be attached by default to the Send Quotation By Email form depending the products in the Sale Order Lines.

Documentation should defined by language, country (none for all), product category or product.

**Comment by pedrobaeza** [comment]
I would say this should be something in OCA/sale-workflow, and includes attachments link to the products in the quotation, so no extra data is needed to be setup. This might limit what to upload to the product record, but it's not normal to upload any other things.

**Comment by dreispt** [comment]
Using Product attachments is a possibility, but it's less featured: relies on "user conventions" and it's easier to misuse.
I would like the user to be able to manage the documentation history, and be able to select the particular documents "active" (to automatically attach to SOs).

I hesitate in proposing this here or in oca/sale-worklow.
Maybe split it into two modules: one for documentation and another for specifically applying it to SOs/Quotations?

**Comment by pedrobaeza** [comment]
Yes, then 2 modules should be: one for putting that information on product to be hosted here, and another for attaching that information in the quotation mail in OCA/sale-workflow.
