### ISSUE TITLE
[RFC] product_secondary_expense_account

### ISSUE THREAD

**Issue by max3903** [OCA/product-attribute#528]
With the anglo-saxon accounting, the same product can sometimes be expensed and sometimes considered a cost of goods sold.

This module adds a secondary expense account on the product category and product to set the expense account and keep the original one for the COGS account.

# Usage

* Go to Product Categories (in Inventory or Accounting)
* Create or select a product category
* Set the secondary expense account
* Go to Products (in Inventory or Accounting)
* Create or select a product
* Go to the Accounting tab
* Set the secondary expense account if you want to overwrite the one from the product category

# Technical Specifications

## product.category

- [ ] Add a required many2one field "Secondary Expense Account" to account.account. The field is company dependent and should use the same logic as the other accounting field (use company property)
- [ ] Add a domain to only show accounts with type = Expense

## product.template

- [ ] Add a many2one field "Secondary Expense Account" to account.account. The field is company dependent and should use the same logic as the other accounting field (use company property)
- [ ] Add a domain to only show accounts with type = Expense
- [ ] Add a method _get_secondary_expense_account to return the one from the product or the one from the product category if empty

**Comment by legalsylvain** [comment]
Make sense. LGTM.

Note : i'd like to have a _get_primary_expense_account in odoo core, to avoid copy past, and allow overload.

Regards.
