### ISSUE TITLE
[10.0] product_multi_images deleted pictures still visible product.product and website

### ISSUE THREAD

**Issue by zeroheure** [OCA/product-attribute#535]
In some hard to reproduce cases, one or two images deleted from product template form are still visible on website e-commerce product page and on product.product form. Those images **can't be deleted**, they come back forever.

However there is a workaround : export the product.product images data, clean the fields and import back.

**Comment by pedrobaeza** [comment]
Unless you have clear steps to reproduce the problem, it's not going to be possible to fix the possible problem...

**Comment by zeroheure** [comment]
I know. But reporting the workaround can help others :-)
