### ISSUE TITLE
product_dimension Rename field length --> product_length

### ISSUE THREAD

**Issue by emagdalenaC2i** [OCA/product-attribute#584]
There is a warning in Travis for product_dimension in v12:

************* Module product_dimension.models.product
product_dimension/models/product.py:22: [W8105(attribute-deprecated), Product] attribute "length" deprecated
product_dimension/models/product.py:72: [W8105(attribute-deprecated), ProductTemplate] attribute "length" deprecated

Should this field be renamed to product_length?
Should be also renamed height --> product_height and width --> product_width?

@rvalyi What do you think?

**Comment by legalsylvain** [comment]
👍
