### ISSUE TITLE
[12.0] product_secondary_unit: ststinfo Off-frame

### ISSUE THREAD

**Issue by qzmxs** [OCA/product-attribute#588]
module: product_secondary_unit
version: 12.0

**Steps to reproduce**
- ...
![image](https://user-images.githubusercontent.com/55458897/76160983-d74f9a00-6169-11ea-8d2d-6b0fda743e05.png)

**Current behavior**

**Expected behavior**

**Comment by sergio-teruel** [comment]
Fixed here: https://github.com/OCA/stock-logistics-warehouse/pull/1081
versions > 12.0 is not affected
Thanks
