### ISSUE TITLE
[12.0] product_pricelist_supplierinfo - Change uom  in sale.order.line

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/product-attribute#610]
When i change unit of measure on sale.order.line the unit price don'ts conversion. It's normal ?

![image](https://user-images.githubusercontent.com/3595132/81261674-daa0be00-9012-11ea-966c-137815af3a44.png)

**Comment by rousseldenis** [comment]
@cubells @pedrobaeza @Nikul-Chaudhary Do you have an advice ?

**Comment by pedrobaeza** [comment]
If you select that product and UoM on purchase orders, is the second price used (put a different one for testing)?

**Comment by marcelsavegnago** [comment]
> If you select that product and UoM on purchase orders, is the second price used (put a different one for testing)?

@pedrobaeza Like this ?

![image](https://user-images.githubusercontent.com/3595132/81324563-87a82480-906d-11ea-98c2-01fedd24823f.png)

![image](https://user-images.githubusercontent.com/3595132/81324666-ad352e00-906d-11ea-8f55-7ef61cc34cf8.png)

![image](https://user-images.githubusercontent.com/3595132/81324463-65aea200-906d-11ea-8ab2-5c7adc9f7986.png)

**Comment by pedrobaeza** [comment]
No, I was talking about using the same product with both product.supplierinfo in a purchase order to see if standard selects second line with that UoM.

**Comment by marcelsavegnago** [comment]
@pedrobaeza 

- I created a new product
- I configured the supplierinfo (supplierinfo only one uom) 
- I created a PO with 2 lines the same product and with different unit of measure.

The price is compute correctly.

![image](https://user-images.githubusercontent.com/3595132/81328877-02743e00-9074-11ea-813a-ade97aa28776.png)

![image](https://user-images.githubusercontent.com/3595132/81328807-e8d2f680-9073-11ea-800f-b93ebc7a9187.png)

**Comment by pedrobaeza** [comment]
OK, my confusion comes from thinking that in the first screenshot you was showing product.supplierinfo, not sales order lines. I will check and tell you back...

**Comment by marcelsavegnago** [comment]
> OK, my confusion comes from thinking that in the first screenshot you was showing product.supplierinfo, not sales order lines. I will check and tell you back...

Ok.. :) Thanks

**Comment by pedrobaeza** [comment]
Should be fixed by #776
