### ISSUE TITLE
Product Brand for 13.0

### ISSUE THREAD

**Issue by dirceubb** [OCA/product-attribute#612]
when i try to install product_brand module on odoo 13.0 community i get this message:

``module 'odoo.api' has no attribute 'multi'`
`can i fix this myself, or are you planning to release this module for 13 version anytime soon?
regards
@OCA-git-bot

**Comment by pedrobaeza** [comment]
The module is here: https://github.com/OCA/brand/tree/13.0/product_brand

**Comment by dirceubb** [comment]
thanks a lot
