### ISSUE TITLE
product_secondary_unit for Variants

### ISSUE THREAD

**Issue by Moto017** [OCA/product-attribute#648]
Use case for different variants with secondary unit.  
Should secondary unit be defined on product.product instead of product template?

**Comment by pedrobaeza** [comment]
I don't see that granularity as needed, as you can define several secondary units in template.

**Comment by Moto017** [comment]
I see.  The default sale/purchase secondary units should then be on product.product instead of product template

**Comment by pedrobaeza** [comment]
Yes, that can be changed, but the module for that is `sale_order_secondary_unit`, not this one.
