### ISSUE TITLE
purchase.order form view

### ISSUE THREAD

**Issue by thomasklosinsky** [OCA/product-attribute#67]
it would be great to have product_brands attribute related in purchase.order (.line) view also to search and select products from brand and name...

Any chance to have it implemented in search logic of that field?

**Comment by pedrobaeza** [comment]
As this is a feature request, not an issue, I close. You can make a PR to include this missing feature as a point in "Known issues / Roadmap" section in the module, so everyone can see it and maybe someone adds the feature.
