### ISSUE TITLE
[RFC] module to propagate "active" value between product variant and template

### ISSUE THREAD

**Issue by legalsylvain** [OCA/product-attribute#750]
Hi all,

here is the need : 
in odoo, for products, we have two fields ``active``, one on the ``product.product`` model, one on the ``product.template`` model. There are not link between both fields.
so, it can occures that an active template has only disabled variant but is still visible. So users looking for products will see a product in a view, but not in the other view that is confusing. It forces the user to disable two times the products to archive it really.

i'm looking for a module ``product_active_propagate`` with the following features : 

- if a user disables a template, it disables all the variants ;
- if a user ensables a template, in enables all the variants ;  
- if a user disables a variant, and if it was the last active variant, it disable also the template ;
- the a user enable a variant, it enables the templates ; 

Do you know an existing module for that features ? 

thanks

**Comment by grindtildeath** [comment]
HI @legalsylvain 

We did report this issue a few weeks ago.

It was actually corrected on 13.0: https://github.com/odoo/odoo/pull/60536
But it seems they couldn't do it for 12.0: https://github.com/odoo/odoo/pull/60648

**Comment by legalsylvain** [comment]
Thanks @grindtildeath : I added your comment in the DEVELOP.rst section, here : 
https://github.com/OCA/product-attribute/pull/752/files#diff-6526aecb539e44c990f1027ca540d81c7a7d22935f237938dcb34f2929816772

BTW, did you tested the module of my PR ? 

thanks !

**Comment by grindtildeath** [comment]
@legalsylvain 
No I didn't test, just thought I'd mentioned this here as the scope was quite similar
