### ISSUE TITLE
Security for product_supplierinfo_for_customer

### ISSUE THREAD

**Issue by sergiocorato** [OCA/product-attribute#761]
Perhaps an additional group to create supplierinfo can be useful? As-is, only `group_system` can create:
https://github.com/OCA/product-attribute/blob/12.0/product_supplierinfo_for_customer/security/ir.model.access.csv#L2

If ok I'll create a PR.

**Comment by pedrobaeza** [comment]
Yes, it can be useful for not having to install *_sale module, but please provide a migration script for adding system users to such group.

**Comment by sergiocorato** [comment]
Do you refer to https://github.com/OCA/sale-workflow/tree/12.0/product_supplierinfo_for_customer_sale ? Or others? I don't see other groups.

**Comment by pedrobaeza** [comment]
Yes, I thought that one included new extra access rules... @carlosdauden @sergio-teruel didn't you add such thing?

**Comment by sergio-teruel** [comment]
I do not remenber this...

**Comment by pedrobaeza** [comment]
OK, then it's good to add as well security for salesman on the same row.

**Comment by pedrobaeza** [comment]
Fixed in #1432
