### ISSUE TITLE
Product State

### ISSUE THREAD

**Issue by lillebutik** [OCA/product-attribute#854]
It would really make sense to add this feature to variants.

**Comment by andreampiovesana** [comment]
I confirm I need this also.
As example if you have a t-shirt in 20 colors and the color pink is end-of-life you can't set.
You can't set all colors end-of-life!
make the change like in https://github.com/OCA/product-attribute/tree/14.0/product_manufacturer

**Comment by andreampiovesana** [comment]
no news?
