### ISSUE TITLE
Feature request : certified labels (ie. organic, fair trade...)

### ISSUE THREAD

**Issue by clonedagain** [OCA/product-attribute#88]
Certified labels like "organic", 'fair-trade", controlled origin appellations etc. impose a few requirements to companies.
- the labels must be clearly indicated on the customer invoices, along with the name/code of the certification organization
- stock, receipts, deliveries, manufacturing and invoices must be auditable, to prove that the rules of the certification are respected.

It would be useful if OCA proposed at least a basic support for this feature.

**Comment by clonedagain** [comment]
We have a private implementation of this which may still contain a few specific parts but could be used as a starting point.
We'll share it if someone else steps up to work on this with us.

Current features are:
- multiple labels per product
- possibility to print the label's logo on invoice lines and delivery slips lines
- possibility to mention the label on the footer of invoices and delivery slips
- show products in green when label requires it
- lock lots if the label demands it, to prevent unwanted stock moves

**Comment by clonedagain** [comment]
@lbellier for your information

**Comment by lbellier** [comment]
@clonedagain : Ok +1

**Comment by pedrobaeza** [comment]
As there's no PR for this, I close.
