### ISSUE TITLE
"duplicate key value violates unique constraint "ir_sequence_type_code_unique" after upgrading product_sequence

### ISSUE THREAD

**Issue by mgielissen** [OCA/product-attribute#90]
After running upgrade I get this error:

openerp.sql_db: bad query: INSERT INTO "ir_sequence_type" ("id", "code", "name", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('ir_sequence_type_id_seq'), 'product.product', 'Product', 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "ir_sequence_type_code_unique"
DETAIL:  Key (code)=(product.product) already exists.

ParseError: "duplicate key value violates unique constraint "ir_sequence_type_code_unique"
DETAIL:  Key (code)=(product.product) already exists.
" while parsing /opt/odoo/custom/addons/product_sequence/data/product_sequence.xml:5, near
<record id="seq_product_auto_type" model="ir.sequence.type">
            <field name="name">Product</field>
            <field name="code">product.product</field>
        </record>

**Comment by mgielissen** [comment]
I deleted the record product.product with "delete from ir_sequence_type where code = 'product.product';" and rerun the module upgrade without problems.

**Comment by pedrobaeza** [comment]
Well, seeing in commit history, XML-ID of the sequence type hasn't been changed, so maybe you were using an intermediate version non-official, and updating you have found this error.

I close as there are no signs of any action in our part.
