### ISSUE TITLE
[14.0] [BUG] product_supplierinfo_for_customer - variant selection not possible

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/product-attribute#986]
**Affected versions**:

[14.0]

Install module product_supplierinfo_for_customer
Create product with variants
In product: tab Sales > Customers, create a new line > click on "product variant"

CURRENT BEHAVIOR

field “product variant” is not displaying any value

EXPECTED BEHAVIOR

Dropdown should display all possible variants for the product template

[VIDEO](https://recordit.co/VFXTDpVzYv)

**Comment by francesco-ooops** [comment]
related to issue https://github.com/odoo/odoo/issues/87192

**Comment by francesco-ooops** [comment]
@OCA/product-maintainers , any help on how to solve this one?

thanks!

**Comment by pedrobaeza** [comment]
Fixed in #1138
